background jobs
diaz47/qna pull request #14
Opened 2017-04-24 14:20 UTC by diaz47

2017-04-24 16:56 UTC, vkurennov requested changes

2017-04-24 16:56 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def subscribe
Гораздо лучше сделать отдельный контроллер подписок, тогда create - это создание подписки, destroy - отмена. Не нужно перегружать контроллер вопросов лишним, помни о единственной ответственности классов.

2017-04-24 16:56 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @subscribe = @question.subscribes.create(user: current_user) if user_signed_in? && !@question.subscribes.exists?(user_id: current_user.id)
У тебя аутентификация первым фильтром стоит, сюда управление даже не дойдет, если юзер не залогинен, так что проверка на `user_signed_in?` смысла не имеет

2017-04-24 16:56 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question.subscribes.create(user: current_user)
Это делается через коллбеки в модели. Не важно, как создается модель, подписка должна быть в любом случа, иначе, придется этот же код как минимум в API дублировать

2017-04-24 16:56 UTC, vkurennov commented on app/models/answer.rb
> +  def notificator_sub
Дай более понятное имя методу, и оно должно начинатсься с глагола, раз это команда

2017-04-24 16:56 UTC, vkurennov commented on app/models/subscribe.rb
> +class Subscribe < ApplicationRecord
Лучше назвать модель Subscription (подписка)

2017-04-24 16:56 UTC, vkurennov commented on app/models/question.rb
> +  has_many :subscribes, dependent: :destroy
Лучше сделать ассоциацию сразу с подписчиками, используя`has_many :through`, тогда у вопроса можно будет сразу получить юзеров-подписчиков, минуя промежуточную модель.

2017-04-24 20:04 UTC, diaz47 commented on app/models/subscribe.rb
> +class Subscribe < ApplicationRecord
я это учту, может быть пока это можно оставить так?  ведь сути не менят

2017-04-25 08:32 UTC, vkurennov requested changes

2017-04-25 08:32 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  before_action :set_question, only: [:show, :destroy, :update, :subscribe, :unsubscribe]
У тебя больше нет экшенов subscribe/unsubscribe

2017-04-25 08:32 UTC, vkurennov commented on app/controllers/subscribes_controller.rb
> +    @subscribe = @question.subscribes.create(user: current_user) if !@question.subscribes.exists?(user_id: current_user.id)
Используй лучше метод `User#subsribed?`

2017-04-25 08:32 UTC, vkurennov commented on app/controllers/subscribes_controller.rb
> +    @subscriber = @question.subscribes.where(user_id: current_user.id).first.destroy if @question.subscribes.exists?(user_id: current_user.id)
И тут используй `User#subsribed?`

2017-04-25 08:32 UTC, vkurennov commented on app/jobs/sub_job.rb
> +    answer.question.subscribes.each do |sub|
Как ты думаешь, зачем мы в `Question` сделали ассоциацию `subscribers`?

2017-04-25 08:32 UTC, vkurennov commented on app/models/subscribe.rb
> +class Subscribe < ApplicationRecord
ок, хотя уметь переименовывать модели тоже полезно. Один раз намучаешься, в следующий раз уже будешь называть сразу нормально. А с другой стороны поймешь, что и это не сложно.

2017-04-25 08:32 UTC, vkurennov commented on app/models/user.rb
> +    @sub = Subscribe.exists?(user_id: id, question_id: question.id)
А зачем тут инстанс-переменная?

2017-04-25 08:32 UTC, vkurennov commented on app/models/user.rb
> +  def subscribed?(question)
А где тесты модели на этот метод?

2017-04-26 08:12 UTC, vkurennov approved these changes

2017-04-26 08:12 UTC, vkurennov commented on Gemfile.lock
> +<<<<<<< HEAD
У тебя закоммичен файл с неразрешенными конфликатми, он не будет работать и будет ошибку выдавать. Надо исправить и закоммитить снова.
Для Gemfile.lock рекомендую просто запустить bundle install, он будет перезаписан, затем его можно закоммитить. Если это будет ошибку выдавать, то можно удалить сначала Gemfile.lock (только с диска, не из репо)

2017-04-26 08:12 UTC, vkurennov commented on spec/models/user_spec.rb
> +      expect(sub_user.subscribed?(question)).to eq true
`expect(sub_user).to be_subscribed`

2017-04-26 09:34 UTC, merged