create other history to questions and answers
diaz47/qna pull request #3
Opened 2017-02-12 20:28 UTC by diaz47

2017-02-13 10:51 UTC, vkurennov requested changes

2017-02-13 10:51 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @question
Можно делать редирект и устанавливать флеш-сообщение в одну строку:  `redirect_to @question, notice: "Your answer successfully created"`

2017-02-13 10:51 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @question
Нельзя делать редирект при невалидном объекте. В этом случае теряется и инфомация о конкретных ошибках валидации и то, что ввел пользователь. Поэтому должен быть рендер страницы с форомой, а в виде должен быть вывод ошибок валидации

2017-02-13 10:51 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.id == @answer.user_id
У нас такая проверка много где потребуется, лучше вынести ее в метод `User#author_of?`

2017-02-13 10:51 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(params[:question_id])
Редирект одинаковый в обоих случаях, надо вынести его из условия

2017-02-13 10:51 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user.id == @question.user_id
примени метод `User#author_of?`

2017-02-13 10:51 UTC, vkurennov commented on app/views/layouts/application.html.erb
> +    <%= user_signed_in? ? link_to("Log out(#{current_user.id})", destroy_user_session_path, method: :delete) : '' %>
А зачем выводить id в ссылке Log out? Это же видит пользователь, зачем ему знать внутренний id?

2017-02-13 10:51 UTC, vkurennov commented on app/views/questions/show.slim
> +-if user_signed_in?
Лучше не показывать ссылку вообще никому, кроме автора. Зачем не-автору видеть ссылку, на которую он не может нажать?

2017-02-13 10:51 UTC, vkurennov commented on app/views/questions/show.slim
>  h2 Create answer
Где-то тут должен быть вывод ошибок валидации

2017-02-13 10:51 UTC, vkurennov commented on app/views/questions/show.slim
> +  -if user_signed_in?
Также не нужно показывать ссылку никому, кроме автора

2017-02-13 10:51 UTC, vkurennov commented on app/views/questions/show.slim
> +    p= link_to 'Delete answer', question_answer_path(question_id: @question, id: answer), method: :delete
Не надо передавать id в url-хелпер, достаточно передавть объекты:  `question_answer_path(@question, answer)`, и можно еще короче, как в формах, передать массив: `[@question, answer]`.

2017-02-13 10:51 UTC, vkurennov commented on spec/acceptance/answer_spec.rb
> +    expect(page).to have_content 'Your answer successfully created'
Нужно проверить, что содержимое ответа появилось на странице

2017-02-13 10:51 UTC, vkurennov commented on spec/acceptance/answer_spec.rb
> +  scenario 'Author of answer try delete question' do
Это отдельная фича - удаление ответов, не надо все мешать в одну спеку. Должны быть спеки для создания ответов, удаления, редактирования (когда оно будет) и т.п.

2017-02-13 10:51 UTC, vkurennov commented on spec/acceptance/answer_spec.rb
> +feature 'Answer for question' do
Это не фича. Фича подразумевает действие - создание, удаление, изменение и т.п.

2017-02-13 10:51 UTC, vkurennov commented on spec/acceptance/answer_spec.rb
> +    expect(page).to have_content 'Your answer was success deleted'
Надо проверить, что после удаления, текста ответа больше нет на странице

2017-02-13 10:51 UTC, vkurennov commented on spec/acceptance/answer_spec.rb
> +  scenario 'Author of answer try delete question' do
И описание теста какое-то странное. Что значит "автор ответа пробует удалить вопрос"?

2017-02-13 10:51 UTC, vkurennov commented on spec/acceptance/answer_spec.rb
> +  scenario 'No Author of answer try delete question' do
Опять старнное описание теста

2017-02-13 10:51 UTC, vkurennov commented on spec/acceptance/answer_spec.rb
> +    fill_in 'Write your answer', with: 'My comment'
Лучше для сценариев, где предполагается наличие объекта, создавать его через фабрики в базе. Потому что если сломается создание ответа через интерфейс, то сломается и этот тест, а если через базу создавать, то тогда удаление будет работать как и прежде.

2017-02-13 10:51 UTC, vkurennov commented on spec/acceptance/answer_spec.rb
> +    click_on 'Delete answer'
А лучше не показывать вообще ссылку на удаление

2017-02-13 10:51 UTC, vkurennov commented on spec/acceptance/answer_spec.rb
> +feature 'Answer for question' do
Не хвататет сценариев:

 - По созданию: проверить, что выводятся ошибки валидации. Все валидации проверять не нужно, это мы делаем в тестах модели, но надо проверить, что пользователь видит информацию хотя бы об одной ошибке валидации

2017-02-13 10:51 UTC, vkurennov commented on spec/acceptance/questions_spec.rb
> +feature 'Questions' do
Опять же это не фича. Раздели на разные фичи для создания, удаления и т.п.

2017-02-13 10:51 UTC, vkurennov commented on spec/acceptance/questions_spec.rb
> +    expect(page).to have_content 'Your question successfully created'
Надо проверить, что на странице есть заголовок и текст вопроса

2017-02-13 10:51 UTC, vkurennov commented on spec/acceptance/questions_spec.rb
> +  scenario 'User can see all questions on page' do
Это также надо вынести в отдельную фичу - просмотр вопросов

2017-02-13 10:51 UTC, vkurennov commented on spec/acceptance/questions_spec.rb
> +    expect(page).to have_content questions[0].title
И желательно, проверить на списке хотя бы в 5 вопросов, причем в цикле

2017-02-13 10:51 UTC, vkurennov commented on spec/acceptance/questions_spec.rb
> +    expect(page).to have_content answers[0].body
Тут тоже надо проверить на списке ответов и тоже они должны быть разными (у тебя только для вопросов сделан sequence в фабриках)

2017-02-13 10:51 UTC, vkurennov commented on spec/acceptance/questions_spec.rb
> +    expect(page).to have_content 'Your question was deleted'
Надо проверить, что заголовка вопроса нет на странцие после удаления

2017-02-13 10:51 UTC, vkurennov commented on spec/acceptance/questions_spec.rb
> +    click_on 'Delete question'
Ему проще не показывать ссылку

2017-02-13 10:51 UTC, vkurennov commented on spec/acceptance/questions_spec.rb
> +feature 'Questions' do
Нужен сценарий на вывод ошибок валидации при создании. А при удалении, надо проверять, что и не залогиненный юзер не видит ссылку на удаление

2017-02-13 10:51 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
То есть, в AnswersController ничего не поменялось, поэтому покрывать тестами нечего? Например, появилось удаление, причем с проверкой на автора. А при создании теперь ответ связывается не только с вопросом, но и с залогиненным юзером. На это все должны быть тесты.

2017-02-13 10:51 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'POST #create' do
Надо проверить, что вопрос связывается с залогиненным юзером

2017-02-13 10:51 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +  describe 'DELETE #destroy' do
Если у тебя где-то в коде есть условие, то это означает, что тестировать надо и вариант, когда условие выполняется и когда не выполняется. Тут как минимум нужно протестировать 2 контекста: автор и не автор.

2017-02-13 10:51 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    it 'delete question from the db' do
Ну вообще, кроме удаления, происходит еще и редирект, который тоже надо протестить

2017-02-13 10:51 UTC, vkurennov commented on spec/models/user_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
А тесты на ассоциации?

2017-02-15 09:15 UTC, vkurennov requested changes

2017-02-15 09:15 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      render :new
У тебя нет экшена new и не должно быть вида для него, да он и не нужен, т.к. форма выводится на странице вопроса. Вот ее и надо рендерить

2017-02-15 09:15 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    unless current_user.id == @answer.user_id
Вынеси эту проверку в метод `User#author_of?` и используй этот метод везде, где нужна проверка на авторство.

2017-02-15 09:15 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    unless current_user.id == @question.user_id
Напиши и используй метод `User#author_of?`

2017-02-15 09:15 UTC, vkurennov commented on app/views/answers/new.slim
> +-if @answer.errors.any?
Не нужно делать вид для new, у тебя же нет такого экшена, нужно сделать паршл и его использовать на странице вопроса

2017-02-15 09:15 UTC, vkurennov commented on app/views/layouts/application.html.erb
> +    <%= user_signed_in? ? link_to("Log out(#{current_user.id})", destroy_user_session_path, method: :delete) : '' %>
Ну и? Зачем id показывать юзеру?

2017-02-15 09:15 UTC, vkurennov commented on app/views/questions/show.slim
> +-if user_signed_in? && current_user.id == @question.user_id
Используй метод `User#author_of?`

2017-02-15 09:15 UTC, vkurennov commented on app/views/questions/show.slim
>  h2 Create answer
Зачем дублировать форму? Вынеси ее в паршл (то, что у тебя в answers/new) и вызывай его здесь

2017-02-15 09:15 UTC, vkurennov commented on app/views/questions/show.slim
> +  -if user_signed_in? && current_user.id == answer.user_id
Используй метод `User#author_of?`

2017-02-15 09:15 UTC, vkurennov commented on spec/acceptance/answer/delete_answer_spec.rb
> +  scenario 'No Author of answer try delete answer' do
Есть еще один сценарий, когда юзер не видит ссылку на удаление: он не залогинен. Это тоже надо проверить (в отдельном сценарии)

2017-02-15 09:15 UTC, vkurennov commented on spec/acceptance/answer/show_answers_spec.rb
> +    expect(page).to have_content 'body3'
Тут надо проверить **список** ответов, хотя бы штук 5, причем, все должны быть разные (используй sequence в фабриках для этого).

2017-02-15 09:15 UTC, vkurennov commented on spec/acceptance/question/add_questions_spec.rb
> +  given(:answers) { create_list(:answer, 2) }
А зачем тебе ответы здесь?

2017-02-15 09:15 UTC, vkurennov commented on spec/acceptance/question/delete_question_sepc.rb
> +  scenario 'No Author of question try delete question' do
И нужен сценарий для незалогиненного юзера

2017-02-15 09:15 UTC, vkurennov commented on spec/acceptance/question/show_questions_spec.rb
> +    expect(page).to have_content questions[0].title
Тут лучше сделать штук 5 вопросов, причем разных, и проверить их в цикле

2017-02-15 09:15 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, answer: attributes_for(:answer), question_id: question }.to change(Answer, :count).by(1)
Почему убрал проверку на связь с вопросом? Нужны 2 теста: один проверяет связь с вопросом, другой- связь с залогиненным юзером

2017-02-15 09:15 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect(answer_user.user_id).to eq user.id
Что ты тут тестируешь? То, что у тебя верно создана фабрика и ты верно поставил у нее связи? Зачем, что это дает? В общем, тест лишний и непосредственно к удалению никакого отношения не имеет.

2017-02-15 09:15 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, id: answer_user, question_id: question, user_id: user }.to change(Answer, :count).by(-1)
user_id не передается в параметрах, мы его берем через current_user в контроллере. Кроме того,  user,  которого ты здесь используешь и тот, которого мы логиним - это два разных объекта. Залогиненный юзер у нас доступен как переменная @user (см. код метода sign_in_user).

В общем, я не вижу, почему этот тест должен пройти, и не уверен, что он проходит

2017-02-15 09:15 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      it 'answer id != user id' do
И опять же тест бессмысленный, зачем проверять свои собственные фабрики? Это никак не влияет на выполнение кода в контроллере

2017-02-15 09:15 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, id: answer, question_id: question, user_id: user}.to change(Answer, :count).by(0)
1. user_id не передается в параметрах
2. Пиши не `change(...).by(0)`,  а `to_not change(...)`

2017-02-15 09:15 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'POST #create' do
Ну и где эта проверка?

2017-02-15 09:15 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +      it 'question user id == user id' do
Тест не имеет смысла

2017-02-15 09:15 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { delete :destroy, id: question_user, user_id: user }.to change(Question, :count).by(-1)
1. user_id не передается в параметрах
2. автор у question_user и залогиненный юзер - это разные юзеры, тест не должен проходить

2017-02-15 09:15 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +      it 'question user id != user id' do
Тест бессмысленный

2017-02-15 09:15 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { delete :destroy, id: question, user_id: user }.to change(Question, :count).by(0)
1. user_id не передается в параметрах
2. `to_not change(...)`

2017-02-15 09:15 UTC, vkurennov commented on spec/support/controller_macros.rb
> +      @user = create(:user)
Вот, обрати внимание, как мы тут создаем юзера. Вот он и есть наш залогиненный юзер в тестах контроллера, а вовсе не тот, которого ты создаешь через let(:user). Это 2 разных юзера.

2017-02-15 09:26 UTC, diaz47 commented on app/views/layouts/application.html.erb
> +    <%= user_signed_in? ? link_to("Log out(#{current_user.id})", destroy_user_session_path, method: :delete) : '' %>
а это я для себя делал чтоб смотреть через кого заходил

2017-02-15 09:27 UTC, diaz47 commented on app/controllers/answers_controller.rb
> +      render :new
я не совсем понимаю как можно это сделать

2017-02-16 09:49 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      render :new
Отрендерить вид questions/show

2017-02-16 10:00 UTC, vkurennov requested changes

2017-02-16 10:00 UTC, vkurennov commented on app/models/user.rb
> +  def author_of?(object)
Где тесты модели на этот метод? Прежде чем писать какой-то код, задай вопрос "есть ли у меня тесты на него?". Если нет, начни с тестов. Подумай, как должен работать этот метод (что должен получать и что возвращать) и реализуй это, шаг за шагом, в тестах. Т.е. сначала, когда метод возвращает true, затем сам метод (если он простой, то его сразу можно написать), затем тест, когда он возвращает false. Если тесты прошли, то все ок, метод рабочий. Если нет, значит, надо его исправить.

2017-02-16 10:00 UTC, vkurennov commented on app/views/questions/show.slim
> +-if user_signed_in? && current_user.id == @question.user_id
Сколько раз нужно написать "Используй метод User#author_of?", чтобы ты его начал использовать?

2017-02-16 10:00 UTC, vkurennov commented on app/views/questions/show.slim
> +p= "Author of question #{@question.user_id}"
Думаю, это лишняя информация. Если уж выводить автора, то либо имя, либо email, а не внутренний id.

2017-02-16 10:00 UTC, vkurennov commented on app/views/questions/show.slim
> +  -if user_signed_in? && current_user.id == answer.user_id
И вновь пишу: используй тут метод `User#author_of?`

2017-02-16 10:00 UTC, vkurennov commented on app/views/questions/show.slim
> +=render 'shared/create_answer'
А зачем его в shared помещать? Помести в `answers/_form`, например.

2017-02-16 10:00 UTC, vkurennov commented on spec/acceptance/answer/delete_answer_spec.rb
> +  scenario 'No Author of answer try delete answer' do
Где сценарий для незалогиненного юзера?

2017-02-16 10:00 UTC, vkurennov commented on spec/acceptance/question/delete_question_sepc.rb
> +  scenario 'No Author of question try delete question' do
И где это сценарий?

2017-02-16 10:00 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, answer: attributes_for(:answer), question_id: question }.to change(Answer, :count).by(1)
Ну а связь с вопросом-то тоже надо проверить.

2017-02-16 10:00 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect{ delete :destroy, id: answer, question_id: question, user: @user }.to change(Answer, :count).by(-1)
user не передается в параметрах. От слова вообще. Он есть у ответа в ассоциациях, и в контроллере мы обращаемся к залогиненному юзеру через current_user. Как видишь, параметр user (или user_id в предыдущем варианте), который ты упорно передаешь, здесь не участвует.

2017-02-16 10:00 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect{ delete :destroy, id: answer, question_id: question }.to change(Answer, :count).by(0)
`to_not change`

2017-02-16 10:00 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { delete :destroy, id: question }.to change(Question, :count).by(0)
`to_not  change`

2017-02-16 11:49 UTC, vkurennov approved these changes

2017-02-16 11:49 UTC, vkurennov commented on spec/acceptance/question/delete_question_spec.rb
> +    expect(page).to_not have_content 'Delete question'
Лучше have_link использовать и не только здесь, а везде, где ссылки проверяются

2017-02-16 11:49 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      it 'sets question_id equal to the curent question' do
Можно было и по-страому: через ассоциации вопроса в change

2017-02-16 11:49 UTC, vkurennov commented on spec/models/user_spec.rb
> +      it "user_id == question_id" do
У тебя универсальный метод, поэтому не нужно его на каждый возможный тип объекта проверять. Достаточно только на вопросе или на ответе проверить, он ведь будет работать с любым типом, у которого есть user_id.

2017-02-16 11:49 UTC, vkurennov commented on spec/models/user_spec.rb
> +        expect(author.author_of?(question)).to eq true
В rspec для методов-предикатов (которые на знак вопроса заканчиваются) есть крутая штука - динамические матчеры. Можно писать так:

`expect(user).to be_author_of(question)`

Т.е. вызов метода переносится после to, добавляется be_ и не указывается знак вопроса. Используй в будущем.

2017-02-16 17:56 UTC, merged