Lesson 7
diaz47/qna pull request #5
Opened 2017-02-22 18:18 UTC by diaz47

2017-02-23 07:21 UTC, vkurennov requested changes

2017-02-23 07:21 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @answers = @question.answers.order(best_answer: :desc)
Это лучше вынести в скоуп и использовать его.

2017-02-23 07:21 UTC, vkurennov commented on app/models/answer.rb
> +    question = self.question
Это не имеет смысла, потому что если просто вызывать `question`, то это и будет то же самое, что `self.question`, то есть, можно сразу писать `question.answers...`, без создания локальной переменной

2017-02-23 07:21 UTC, vkurennov commented on app/models/answer.rb
> +    self.best_answer = true
Используй update!

2017-02-23 07:21 UTC, vkurennov commented on app/views/answers/_answer.slim
> +  -if user_signed_in? && current_user.author_of?(@question) && answer.best_answer === false
Что это такое в конце? Не сравнивай с true/false, это и так логическое значение, его не надо сравнивать. Если best_answer  вернет true, условие выполнится, если false, то нет. Если нужно инвертированное условие, используй отрицание.

2017-02-23 07:21 UTC, vkurennov commented on app/views/questions/update.js.erb
> +  $('.title_question').html("<%= @question.title %>");
Можно было бы сразу весь блок вопроса обновить, а не по-отдельности

2017-02-23 07:21 UTC, vkurennov commented on config/routes.rb
> +  match '/answers/select_best_answer/(:id)', to:'answers#select_best_answer', via: 'patch', as:'select_best_answer'
Это делается не так.  А вот так:

```
resources :answers do
  patch :select_best_answer, on: :member
end
```

2017-02-23 07:21 UTC, vkurennov commented on spec/acceptance/answer/select_best_answer_spec.rb
> +  scenario 'Author of question try to select best question' do
Надо проверить, что лучший ответ первый в списке

2017-02-23 07:21 UTC, vkurennov commented on spec/acceptance/answer/select_best_answer_spec.rb
> +feature 'Select best answer' do
Также нужен сценарий, когда лучший ответ уже есть, и юзер выбирает другой лучший ответ

2017-02-23 07:21 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect(answer.body).to eq answer.body
Тест не имеет смысла. Ты сравниваешь значение с самим собой. Как он может не пройти? Разве есть ситуация, при которой answer.body  не будет равен самому себе?

2017-02-23 07:21 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect(answer.best_answer).to eq true
`expect(answer).to be_best_answer`
` expect(prev_answer).to_not be_best_answer`

2017-02-23 07:21 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      it 'change attribute for answer and prev-answer' do
Тест проходит? У тебя на момент выполнения запроса нет никаких ответов, ведь они заданы через обычный let, который выполняется в момент вывзова.

2017-02-23 07:21 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +          expect(question.title).to_not eq 'My new title'
Ты же пустое значение передаешь в качестве title, а сравниваешь не с пустым. Если вдруг, title обновится и станет пустым, этот тест пройдет, ведь `"" != 'My new title'`

2017-02-23 07:21 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(answer.best_answer).to eq true
expect(answer).to be_best_answer

2017-02-23 07:21 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(prev_answer.best_answer).to eq false
expect(prev_answer).to_not be_best_answer

2017-02-23 07:21 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      prev_answer.reload
Вот до этой строки у тебя не существует объекта prev_answer. А в момент вызова, он создается, и у него флаг должен быть true, тест не пройдет.

2017-02-23 07:27 UTC, diaz47 commented on app/views/questions/update.js.erb
> +  $('.title_question').html("<%= @question.title %>");
у меня почему то не работает если весь блок выводить

2017-02-24 06:26 UTC, vkurennov approved these changes

2017-02-24 06:26 UTC, vkurennov commented on app/views/questions/update.js.erb
> +  $('.title_question').html("<%= @question.title %>");
Надо разобраться почему.

2017-02-24 06:26 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        answer
Используй `let!`, чтобы создавать данные, которые нужны до теста

2017-02-24 07:25 UTC, merged