add rating to question/answer
diaz47/qna pull request #8
Opened 2017-03-18 07:10 UTC by diaz47

2017-03-18 11:47 UTC, vkurennov requested changes

2017-03-18 11:47 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @vote = @answer.votes.new(value: params[:value], user_id: current_user.id)
Если значение голоса приходит из параметров, то легко сделать накрутку

2017-03-18 11:47 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @user = @answer.votes.find_by user_id: @vote_user.id
Аргументы метода указывай в скобках, так лучше читается

2017-03-18 11:47 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @vote_user = User.find(params[:user_id])
Зачем тебе юзера грузить (и передавать в параметрах), если запрос заведомо от `current_user`?

2017-03-18 11:47 UTC, vkurennov commented on app/controllers/concerns/VoteFor.rb
> +module VoteFor
И зачем консерн, который нигде не используется?

2017-03-18 11:47 UTC, vkurennov commented on app/controllers/concerns/VoteFor.rb
> +  def vote
Это должно быть в моделях, а не в контроллере, потому что это бизнес-логика

2017-03-18 11:47 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def vote
Дублирование с ответами. Вынеси эти методы в консерн и сделай универсальными

2017-03-18 11:47 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @vote_user = User.find(params[:user_id])
И опять же юзер не нужен, т.к. есть current_user

2017-03-18 11:47 UTC, vkurennov commented on app/models/concerns/Votable.rb
> +module Votable
Еще один не используемый консерн

2017-03-18 11:47 UTC, vkurennov commented on app/views/answers/_answer.slim
> +        = link_to raw("<i class='fa fa-thumbs-o-up' aria-hidden='true'></i> Vote for"), vote_answer_path(answer.id, current_user.id, value: 1),  method: :post
link_to умеет принимать блок, куда можно вставить внутренний html, не прибегая к raw

2017-03-18 11:47 UTC, vkurennov commented on app/views/questions/show.slim
> +        = link_to raw("<i class='fa fa-thumbs-o-down' aria-hidden='true'></i> Vote against"), vote_question_path(@question.id, current_user.id, value: -1),  method: :post
прочитай про polymorphic_path, чтобы сделать паршл голосования универсальным

2017-03-18 11:47 UTC, vkurennov commented on config/routes.rb
> +  match '/questions/:question_id/vote/:user_id', to:'questions#vote', via: 'post', as:'vote_question'
Плохо, используй кастомные экшены и консерны в роутах

2017-03-19 20:41 UTC, diaz47 commented on app/controllers/questions_controller.rb
> +  def vote
а можно использовать не концер, а к примеру просто хелпер ?

2017-03-20 08:34 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def vote
Нет, нельзя. А в чем по-твоему отличие? Ты же просто выносишь в модуль нужные методы и переиспользуешь их в различных классах

2017-03-20 08:38 UTC, vkurennov requested changes

2017-03-20 08:38 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def vote
В общем, вынести это в консерны, надо тренироваться. У тебя тут код на 99% совпадает, нужно только переменные одинаково назвать и загрузить в них нужный объект.

2017-03-20 08:38 UTC, vkurennov commented on config/routes.rb
> +    collection do
Почему collection, если голосование идет за конкретный вопрос/ответ? Должен быть member, тогда в url будет id  объекта, иначе как ты определишь, за какой объект голосовать?

2017-03-20 08:38 UTC, vkurennov commented on app/views/shared/_vote.slim
> +    = link_to polymorphic_url([:vote, path_arg, klass], value: 'yes', "#{element_param}": element.id), method: :post do
Не надо id в параметрах передавать, в роутинге определи экшены для memeber, тогда у тебя id будет в url

2017-03-20 18:26 UTC, vkurennov requested changes

2017-03-20 18:26 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def set_vote_data
У тебя же в консерне такой метод есть, зачем он здесь переопределен?

2017-03-20 18:26 UTC, vkurennov commented on app/views/answers/delete_vote.js.erb
> +$('#answer_sum_<%=@element.id%>').html("Rating answer: <%= @element.votes.sum(:value) %>");
Это что? У нас в задании четко сказано, что все это нужно сделать через JSON, в этом суть задания

2017-03-20 18:26 UTC, vkurennov commented on config/routes.rb
>      resources :answers do
Сделай ресурс shallow, тогда не нужно будет передавать еще и question_id, там где достаточно только id ответа. Это позволит сделать консерн моделей более универсальным

2017-03-21 08:47 UTC, vkurennov approved these changes

2017-03-21 17:35 UTC, merged